### ISSUE TITLE
PLDM Unpack fails on null-terminated strings

### ISSUE THREAD

**Issue by daxie117** [NVIDIA/PLDM-unpack#1]
Given that PLDM specification considers null bytes to be valid characters, and that subsequent iterations of the specification (1.1+) explicitly call for null terminated strings, it is expected that the unpacking tool be able to handle null terminated strings. However, this results in an "embedded null byte" value error.

https://www.dmtf.org/sites/default/files/standards/documents/DSP0267_1.0.1.pdf : Table 20 specifies the string types in the update spec.

The spec implies that NULL characters are considered part of the ASCII character set when referring to default values. And in the subsequent publication of the base spec (1.1) (https://www.dmtf.org/sites/default/files/standards/documents/DSP0240_1.1.0.pdf), the spec explicitly enforces that strings be null terminated.

**Comment by alishajo2** [comment]
Issue fixed here https://github.com/NVIDIA/PLDM-unpack/pull/2
